# -*- coding: utf-8 -*-
"""Iris_Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJzo4ClfXP8o9HiGE3Z-0RGibCRyh91w
"""

import seaborn as sns
import pandas as pd

df = sns.load_dataset('iris')
df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('iris')
df.head()

df.info()

sns.scatterplot(x='sepal_length', y='petal_length', hue='species', data=df)
plt.title("Scatter Plot")
plt.show()

df['sepal_length'].hist()
plt.title("Histogram of Sepal Length")
plt.show()

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()

sns.violinplot(x='species', y='petal_length', data=df)
plt.show()

sns.countplot(x='species', data=df)
plt.title("Species Count")
plt.show()