# -*- coding: utf-8 -*-
"""Titanic EDA Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDL2-QKJArKRiBPRv2VsUku_n1qptINn
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('train.csv.csv')
df.head()

df.head()

df.info()

df.describe()

df.isnull().sum()

df['Age'].fillna(df['Age'].mean(), inplace=True)

df.isnull().sum()

df['Sex'] = df['Sex'].map({'male':0, 'female':1})

df['Embarked'] = df['Embarked'].map({'S':0,'C':1,'Q':2})

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.show()

sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.show()